In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
import sys
sys.path.append("../..")

In [7]:
from pypots.data.generating import gene_physionet2012
from pypots.utils.random import set_random_seed
#from global_config import RANDOM_SEED
#set_random_seed(RANDOM_SEED)

import random
random.seed(9001)

# Load the PhysioNet-2012 dataset, disable artificially-missing values for evaluation
physionet2012_dataset = gene_physionet2012(artificially_missing_rate=0.3)
 
# Take a look at the generated PhysioNet-2012 dataset, you'll find that everything has been prepared for you, 
# data splitting, normalization, additional artificially-missing values for evaluation, etc.
print(physionet2012_dataset.keys())

2025-03-24 09:23:31 [INFO]: You're using dataset physionet_2012, please cite it properly in your work. You can find its reference information at the below link:
https://github.com/WenjieDu/TSDB/tree/main/dataset_profiles/physionet_2012
2025-03-24 09:23:31 [INFO]: Dataset physionet_2012 has already been downloaded. Processing directly...
2025-03-24 09:23:31 [INFO]: Dataset physionet_2012 has already been cached. Loading from cache directly...
2025-03-24 09:23:31 [INFO]: Loaded successfully!

KeyError: 'set-a'

In [1]:
import tsdb
physionet2012_dataset = tsdb.load('physionet_2012')

2025-03-24 09:34:54 [INFO]: You're using dataset physionet_2012, please cite it properly in your work. You can find its reference information at the below link:
https://github.com/WenjieDu/TSDB/tree/main/dataset_profiles/physionet_2012
2025-03-24 09:34:54 [INFO]: Dataset physionet_2012 has already been downloaded. Processing directly...
2025-03-24 09:34:54 [INFO]: Dataset physionet_2012 has already been cached. Loading from cache directly...
2025-03-24 09:34:54 [INFO]: Loaded successfully!

In [2]:
physionet2012_dataset['X']

Parameter,ALP,ALT,AST,Age,Albumin,BUN,Bilirubin,Cholesterol,Creatinine,DiasABP,...,SaO2,SysABP,Temp,Time,TroponinI,TroponinT,Urine,WBC,Weight,pH
0,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,71.8,NaN
1,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,36.6,1,NaN,NaN,NaN,NaN,71.8,NaN
2,NaN,NaN,NaN,35.0,NaN,68.0,NaN,NaN,2.3,NaN,...,NaN,NaN,NaN,2,NaN,0.15,120.0,15.3,71.8,NaN
3,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3,NaN,NaN,60.0,NaN,71.8,NaN
4,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,NaN,NaN,60.0,NaN,71.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541986,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,43,NaN,NaN,NaN,NaN,45.5,NaN
541987,NaN,NaN,NaN,50.0,NaN,46.0,NaN,NaN,6.8,NaN,...,NaN,NaN,NaN,44,NaN,NaN,NaN,10.1,NaN,NaN
541988,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,34.3,45,NaN,NaN,NaN,NaN,45.5,NaN
541989,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,45.5,NaN
541990,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,47,NaN,NaN,NaN,NaN,45.5,NaN

In [41]:
physionet2012_dataset['X']

Parameter,ALP,ALT,AST,Age,Albumin,BUN,Bilirubin,Cholesterol,Creatinine,DiasABP,...,SaO2,SysABP,Temp,Time,TroponinI,TroponinT,Urine,WBC,Weight,pH
0,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,71.8,NaN
1,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,36.6,1,NaN,NaN,NaN,NaN,71.8,NaN
2,NaN,NaN,NaN,35.0,NaN,68.0,NaN,NaN,2.3,NaN,...,NaN,NaN,NaN,2,NaN,0.15,120.0,15.3,71.8,NaN
3,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3,NaN,NaN,60.0,NaN,71.8,NaN
4,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,NaN,NaN,60.0,NaN,71.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541986,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,43,NaN,NaN,NaN,NaN,45.5,NaN
541987,NaN,NaN,NaN,50.0,NaN,46.0,NaN,NaN,6.8,NaN,...,NaN,NaN,NaN,44,NaN,NaN,NaN,10.1,NaN,NaN
541988,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,34.3,45,NaN,NaN,NaN,NaN,45.5,NaN
541989,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,45.5,NaN
541990,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,47,NaN,NaN,NaN,NaN,45.5,NaN

In [39]:
physionet2012_dataset['X'].shape, physionet2012_dataset['y'].shape, len(physionet2012_dataset['static_features'])

((541991, 43), (11988, 1), 4)

In [33]:
for dataset_name in chosen_classes:
    dataset = tsdb.load(dataset_name)
    print(dataset_name, dataset.keys())
    for key in dataset.keys():
        try:
            print(key, dataset[key].shape)
        except:
            print(key, len(dataset[key]))
    
    #try:
    #    X, y = physionet2012_dataset['X'], physionet2012_dataset['y']

2025-03-19 18:27:11 [INFO]: You're using dataset ucr_uea_GunPoint, please cite it properly in your work. You can find its reference information at the below link:
https://github.com/WenjieDu/TSDB/tree/main/dataset_profiles/ucr_uea_datasets
2025-03-19 18:27:11 [INFO]: Start downloading...
Downloading GunPoint.zip: 100%|██████████████| 425k/425k [00:00<00:00, 5.52MB/s]
2025-03-19 18:27:11 [INFO]: Successfully downloaded data to /var/folders/7s/75p3d4f145qfrrzfq5vskssc0000gn/T/tmpwxy77g95/GunPoint.zip
2025-03-19 18:27:11 [INFO]: Successfully extracted data to /Users/louis/.pypots/tsdb/ucr_uea_GunPoint
2025-03-19 18:27:11 [INFO]: Successfully saved to /Users/louis/.pypots/tsdb/ucr_uea_GunPoint/ucr_uea_GunPoint_cache.pkl
2025-03-19 18:27:11 [INFO]: Loaded successfully!

ucr_uea_GunPoint dict_keys(['X_train', 'y_train', 'X_test', 'y_test'])
X_train (50, 1, 150)
y_train (50,)
X_test (150, 1, 150)
y_test (150,)

In [23]:
X.shape, y.shape

((541991, 43), (11988, 1))

In [22]:
from sklearn.model_selection import train_test_split

X, y = physionet2012_dataset['X'], physionet2012_dataset['y']

X_train, X_test, y_train, y_test = train_test_split(X, y)

ValueError: Found input variables with inconsistent numbers of samples: [541991, 11988]